on:
  push:
    branches:
      - v2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://hb0730:${{ secrets.SYNC_TOKEN }}@github.com/hb0730/pure-admin-thin.git"
          source_branch: "v2"
          destination_repo: "https://hb0730:${{ secrets.SYNC_TOKEN }}@github.com/hb0730/boot-admin-ui.git"
          destination_branch: "v4"
